[package]
name = "promql"
description = "Parse PromQL query into AST"
version = "0.1.0"
edition = "2021"
authors = ["Yuanbo <bobo@greptime.com>"]
keywords = ["promql", "prometheus"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfgrammar = "0.12"
lazy_static = "1.4.0"
lrlex = "0.12.0"
lrpar = "0.12.0"

[build-dependencies]
cfgrammar = "0.12"
lrlex = "0.12.0"
lrpar = "0.12.0"
