name: License checker

on:
  push:
    branches:
    - develop
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  license-header-check:
    name: license-header-check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check License Header
      uses: apache/skywalking-eyes/header@main
